(asdf:oos 'asdf:load-op :contextl)
(compile-file "figure-editor.lisp")
(load "figure-editor")
(in-package :contextl-user)
(run-test)

#+abcl (extensions:quit)
#+allegro (excl:exit)
#+clozure (ccl:quit)
#+cmu (ext:quit)
#+ecl (si:quit)
#+sbcl (sb-ext:quit)
