(asdf:oos 'asdf:load-op :contextl)
(compile-file "figure-editor-2.lisp")
(load "figure-editor-2")
(in-package :contextl-user)
(run-test-2)

#+abcl (extensions:quit)
#+allegro (excl:exit)
#+clozure (ccl:quit)
#+cmu (ext:quit)
#+ecl (si:quit)
#+sbcl (sb-ext:quit)
